# Generated by Django 2.0.9 on 2019-11-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='recipient_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
