# Generated by Django 2.0.9 on 2019-11-28 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20191116_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Delivery',
            new_name='delivery',
        ),
    ]
