# Generated by Django 3.1.13 on 2021-11-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_item_is_pulled'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_type',
            field=models.IntegerField(choices=[(1, 'White Glove'), (2, 'Curbside')], default=1),
        ),
        migrations.AddField(
            model_name='delivery',
            name='online_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
