# Generated by Django 4.1.3 on 2022-11-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20211119_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='online_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='shopify id'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='clover order number'),
        ),
    ]
